# Generated by Django 3.1.7 on 2021-03-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210328_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
