# Generated by Django 3.1.7 on 2021-04-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20210401_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='diaryuser',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='diaryuser',
            name='invites_left',
        ),
    ]
