# Generated by Django 3.1.7 on 2021-04-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20210427_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryuser',
            old_name='mail_verified',
            new_name='email_verified',
        ),
    ]
