# Generated by Django 3.1.7 on 2021-04-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20210427_0432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'date')},
        ),
    ]
