# Generated by Django 3.2.1 on 2021-05-10 12:21

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20210427_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, validators=[diary.models.DiaryUser.validate_phone_number]),
        ),
    ]
