# Generated by Django 3.2.1 on 2021-05-30 00:57

import diary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_diaryuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=diary.models.get_image_name, verbose_name='image')),
                ('thumbnail', models.ImageField(blank=True, upload_to=diary.models.get_image_name, verbose_name='image thumbnail')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diary.post', verbose_name='Post')),
            ],
        ),
    ]
