# Generated by Django 3.2.1 on 2021-05-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_convert_image_to_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
