# Generated by Django 3.2.1 on 2021-06-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
