# Generated by Django 3.2.1 on 2021-06-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
