FROM python:3.9.5-buster
LABEL maintainer="lukas@fnordserver.eu"
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apt update && apt install -y git

COPY pyproject.toml .
COPY poetry.lock .

RUN pip install --no-cache-dir poetry
RUN poetry install
RUN poetry add gunicorn

COPY . .
RUN poetry run ./manage.py collectstatic --noinput

RUN mkdir -p /data/redis
RUN ln -s /data/settings_local.py shortdiary/settings_local.py
RUN ln -s /data/asset asset

HEALTHCHECK CMD curl --fail http://127.0.0.1:8000/ || exit 1
CMD ["poetry", "run", "gunicorn", "shortdiary.wsgi", "-b", "[::]:8000", "-w", "6"]
