FROM python:3.9.13-bullseye
LABEL maintainer="lukas@fnordserver.eu"
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apt update && apt install -y git

COPY pyproject.toml .
COPY poetry.lock .

RUN pip install --no-cache-dir poetry
RUN poetry install

COPY . .

RUN ln -s /data/settings_local.py shortdiary/settings_local.py

HEALTHCHECK CMD poetry run ./manage.py qinfo || exit 1
CMD ["poetry", "run", "./manage.py", "qcluster"]
